#pragma once

#include <Arduino.h>

/*
  BIGTREETECH Octopus Pro F446 board profile for the PAROL6 port.

  Physical motor connector order on the Octopus board:
  MOTOR0, MOTOR1, MOTOR2, MOTOR2_2, MOTOR3, MOTOR4, MOTOR5, MOTOR6, MOTOR7.

  MOTOR2_2 is an extra physical connector / duplicate MOTOR2 area. It is not
  logical Joint4. Logical index 3 is MOTOR3 / Joint4, physically after MOTOR2_2.
*/

// MOTOR0 / Joint1
#define OCTOPUS_MOTOR0_STEP PF13
#define OCTOPUS_MOTOR0_DIR PF12
#define OCTOPUS_MOTOR0_CS PC4
#define OCTOPUS_MOTOR0_EN PF14

// MOTOR1 / Joint2
#define OCTOPUS_MOTOR1_STEP PG0
#define OCTOPUS_MOTOR1_DIR PG1
#define OCTOPUS_MOTOR1_CS PD11
#define OCTOPUS_MOTOR1_EN PF15

// MOTOR2 / Joint3
#define OCTOPUS_MOTOR2_STEP PF11
#define OCTOPUS_MOTOR2_DIR PG3
#define OCTOPUS_MOTOR2_CS PC6
#define OCTOPUS_MOTOR2_EN PG5

// MOTOR3 / Joint4
#define OCTOPUS_MOTOR3_STEP PG4
#define OCTOPUS_MOTOR3_DIR PC1
#define OCTOPUS_MOTOR3_CS PC7
#define OCTOPUS_MOTOR3_EN PA0

// MOTOR4 / Joint5
#define OCTOPUS_MOTOR4_STEP PF9
#define OCTOPUS_MOTOR4_DIR PF10
#define OCTOPUS_MOTOR4_CS PF2
#define OCTOPUS_MOTOR4_EN PG2

// MOTOR5 / Joint6
#define OCTOPUS_MOTOR5_STEP PC13
#define OCTOPUS_MOTOR5_DIR PF0
#define OCTOPUS_MOTOR5_CS PE4
#define OCTOPUS_MOTOR5_EN PF1

// Shared TMC SPI
#define OCTOPUS_SPI_MOSI PA7
#define OCTOPUS_SPI_MISO PA6
#define OCTOPUS_SPI_SCK PA5

#define OCTOPUS_TMC_R_SENSE 0.075f

// Stop0..Stop5 optocoupler / LIMIT inputs
#define OCTOPUS_STOP0_LIMIT1 PG6
#define OCTOPUS_STOP1_LIMIT2 PG9
#define OCTOPUS_STOP2_LIMIT3 PG10
#define OCTOPUS_STOP3_LIMIT4 PG11
#define OCTOPUS_STOP4_LIMIT5 PG12
#define OCTOPUS_STOP5_LIMIT6 PG13

#ifdef PAROL6_BOARD_OCTOPUS_PRO_F446

#define PUL1 OCTOPUS_MOTOR0_STEP
#define DIR1 OCTOPUS_MOTOR0_DIR
#define SELECT1 OCTOPUS_MOTOR0_CS
#define GLOBAL_ENABLE OCTOPUS_MOTOR0_EN

#define PUL6 OCTOPUS_MOTOR1_STEP
#define DIR6 OCTOPUS_MOTOR1_DIR
#define SELECT6 OCTOPUS_MOTOR1_CS
#define ENABLE_M1 OCTOPUS_MOTOR1_EN

#define PUL5 OCTOPUS_MOTOR2_STEP
#define DIR5 OCTOPUS_MOTOR2_DIR
#define SELECT5 OCTOPUS_MOTOR2_CS
#define ENABLE_M2 OCTOPUS_MOTOR2_EN

#define PUL4 OCTOPUS_MOTOR3_STEP
#define DIR4 OCTOPUS_MOTOR3_DIR
#define SELECT4 OCTOPUS_MOTOR3_CS
#define ENABLE_M3 OCTOPUS_MOTOR3_EN

#define PUL2 OCTOPUS_MOTOR4_STEP
#define DIR2 OCTOPUS_MOTOR4_DIR
#define SELECT2 OCTOPUS_MOTOR4_CS
#define ENABLE_M4 OCTOPUS_MOTOR4_EN

#define PUL3 OCTOPUS_MOTOR5_STEP
#define DIR3 OCTOPUS_MOTOR5_DIR
#define SELECT3 OCTOPUS_MOTOR5_CS
#define ENABLE_M5 OCTOPUS_MOTOR5_EN

#define MOSI OCTOPUS_SPI_MOSI
#define MISO OCTOPUS_SPI_MISO
#define SCK OCTOPUS_SPI_SCK

#ifndef R_SENSE
#define R_SENSE OCTOPUS_TMC_R_SENSE
#endif

#define LIMIT1 OCTOPUS_STOP0_LIMIT1
#define LIMIT2 OCTOPUS_STOP1_LIMIT2
#define LIMIT3 OCTOPUS_STOP2_LIMIT3
#define LIMIT4 OCTOPUS_STOP3_LIMIT4
#define LIMIT5 OCTOPUS_STOP4_LIMIT5
#define LIMIT6 OCTOPUS_STOP5_LIMIT6

#define FLASH_SELECT PA4

#define SUPPLY_ON_OFF PE11
#define SUPPLY_BUTTON_STATE PE11

#define INPUT1 PC15
#define INPUT2 PC14
#define OUTPUT1 PA2
#define OUTPUT2 PA3

#define ESTOP PG15

#define LED1 PB10
#define LED2 PB11

#define USB_D_PLUS PA12
#define USB_D_MINUS PA11

#define CAN1TX PB9
#define CAN1RX PB8
#define CAN2TX PB13
#define CAN2RX PB12

#define VBUS PB0

#endif
