
[env:octopus_pro_f446]
platform = ststm32
board = nucleo_f446ze
framework = arduino
board_build.mcu = stm32f446ze
board_build.f_cpu = 180000000L
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 3000000
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_NANOLIB_FLOAT_PRINTF
    -D USBCON
    -D USBD_USE_CDC
    -D HAL_PCD_MODULE_ENABLED
    -D SERIAL_USB
lib_deps =
    teemuatlut/TMCStepper @ ^0.7.3
    waspinator/AccelStepper @ ^1.64
